export * from './HomePage'
export * from './Admission'
export * from './Admissionsuccess'
export * from './Dashboard'
export * from './Landingpage'
export * from './Login'
export * from './Register'
export * from './Registrationsuccess'